apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coach-app
  namespace: coach-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: coach.hardwarestartup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - coach.hardwarestartup.com
      secretName: newapp-tls